gog_cart_api:
    type: rest
    resource: gog_cart.controller.rest
    prefix: /cart
    name_prefix: gog_api_

gog_api_post_cart:
    path: /cart
    methods: [ POST ]
    defaults: { _controller: gog_cart.controller.rest:postCartAction }

gog_api_put_cart_add_product:
    path: /cart/{cartCode}/add
    methods: [ PUT ]
    defaults: { _controller: gog_cart.controller.rest:putCartAddProductAction }

gog_api_delete_cart_product:
    path: /cart/{cartCode}/product/{productId}/delete
    methods: [ DELETE ]
    defaults: { _controller: gog_cart.controller.rest:deleteProductAction }